Player restrictions for number of items on the market: 5
Cunstom Post: "欢迎使用"
Max Price for Single Item: 100
Least Price for Single Item: 10
Item max amount: 256
# 只允许修改主页的名称 和 图片路径
# 请不要更改顺序!!!!
Title: "§7[§cS§6e§el§al§bM§9a§dr§ck§6e§et§7]"
Home page:
  Item Market:
    Alias: "物品市场"
    path to icon: "textures/ui/MashupIcon"
  My Items:
    Alias: "我的商品"
    path to icon: "textures/ui/Friend2"
  Search Items:
    Alias: "查找商品"
    path to icon: "textures/ui/magnifyingGlass"
  Blacklisted Items:
    Alias: "黑名单物品"
    path to icon: "textures/blocks/barrier"
  Market Information:
    Alias: "市场信息"
    path to icon: "textures/ui/mute_off"
# 请不要随意修改，否则玩家上架的
# 物品将不会显示

Custom Class:
  Block: "textures/blocks/brick"
  Tool: "textures/items/diamond_pickaxe"
  Food: "textures/items/bread"
  Other: "textures/ui/inventory_icon"


