name: SellMarket
main: market.sMarket
version: 1.6.0
api: "1.0.8"
author: 若水
load: POSTWORLD
loadbefore:
  - AutoUpData
commands:
  sm:
    usage: /sm 帮助
    description: "交易市场"
    aliases:
      - 交易
      - 黑市
